- name: add nginx repo
  template: src=../templates/nginx.list.j2 dest=/etc/apt/sources.list.d/nginx.list
- name: add nginx repo key
  apt_key: url=http://nginx.org/keys/nginx_signing.key  state=present
- name: install nginx 
  apt: name=nginx  update_cache=yes state=present
