- name: added in 2.4, previously you used 'include'
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: create sites-enabled directory and sites-available
  file:  name={{ item }} state=directory
  with_items: "{{ sites }}"
- name: modify config nginx
  template:  src=../templates/nginx.conf.j2  dest=/etc/nginx/nginx.conf
  notify: restart nginx
- name: generate vhost config
  template: src=../templates/vhost.conf.j2   dest=/etc/nginx/sites-available/{{ hostname }}.conf
  notify: restart nginx
- name: create logs directory
  file: name=/var/log/nginx/{{ hostname }} state=directory  
- name: create links to enable vhost
  file: src=/etc/nginx/sites-available/{{ hostname }}.conf  dest=/etc/nginx/sites-enabled/{{ hostname }}.conf state=link
  notify: restart nginx  
