- name: copy nginx repo
  copy: src=../files/nginx.repo  dest=/etc/yum.repos.d/nginx.repo  owner=root mode=0644 
- name: install nginx 
  yum: name=nginx  state=present
- name: ensure service nginx is running
  service: name=nginx state=started enabled=yes  
